### ISSUE TITLE
Could you provide an exe installation package? It would be more convenient, as the method described is too difficult for beginners.

### ISSUE THREAD

**Issue by ictsmc** [Shreyan1/WhisperMe-Audio-Transcriber#4]
Could you provide an exe installation package? It would be more convenient, as the method described is too difficult for beginners.

**Comment by Shreyan1** [comment]
Hey @ictsmc , sure we will try to make a .exe package soon. In the meantime, just try these steps -
### For Installation 👨‍💻
1. **Clone the Repository** : ` git clone https://github.com/Shreyan1/WhisperMe.git ` ; `cd WhisperMe`
2. **Install Dependencies** : ` pip install -r requirements.txt `
3. **Add the API key** : Add your OpenAI developer API key to `apikey.py`
4. **Launch WhisperMe [on Linux and MacOS]** : `./run.sh` on Linux or MacOS ; `.\run.bat` on Windows using Powershell


and that's it. You can try these steps, and if it doesn't work for you, just let me know once via email - [shreyan.github@gmail.com](shreyan.github@gmail.com) or you can create another issue here. I'm happy to help you anytime.
